### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by cscherrer** [oxinabox/AutoPreallocation.jl#19]
Thanks @oxinabox for putting this together, looks really handy.

The README seems to need an update. It fails as written:
```julia
julia> x, preallocated_f = preallocate(f, A, B, C);
ERROR: MethodError: no method matching preallocate(::typeof(f), ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2})
```

Maybe the last three evaluations should be something like

```julia
julia> preallocated_f = preallocate(f);

julia> @btime f($A, $B, $C);
  22.974 ms (4 allocations: 15.26 MiB)

julia> @btime preallocated_f($A, $B, $C);
  21.954 ms (6 allocations: 288 bytes)
```

**Comment by Roger-luo** [comment]
Hi I believe you are using a release version. The latest master has a break change. This README is the latest API on master branch.

**Comment by cscherrer** [comment]
Oh haha ok. Thanks for clarifying @Roger-luo

**Comment by oxinabox** [comment]
@Roger-luo  we really should be tagging a release after every PR.
Is there anything blocking a release being tagged now, do you know?

**Comment by Roger-luo** [comment]
I'm planning to tag one after the docs are setup.

**Comment by Roger-luo** [comment]
but that won't change anything actually, so should tag one now I think.

**Comment by oxinabox** [comment]
I have tagged one, looks like for some reason even though you have commit rights, JuliaRegistrator won't listen to you?
